use_frameworks!

platform :ios, '10.0'

target 'Go23EthereumAddress_Example' do
  pod 'Go23EthereumAddress', :path => '../'

  target 'Go23EthereumAddress_Tests' do
    inherit! :search_paths

    
  end
end
